name: leanprover

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LEAN_TOOLCHAIN=v4.15.0
    network_mode: host
    command:
      - /bin/bash
      - -c
      - |
        git clone https://github.com/leanprover-community/mathlib4 ~/mathlib --depth 1 &&
        cd ~/mathlib &&
        lake exe cache get &&
        lake build &&
        lake test
